server:
  port: 8081

spring:
  application:
    name: project-service

  datasource:
    url: jdbc:postgresql://dpg-d2li9njuibrs73f9il7g-a.singapore-postgres.render.com/project_service
    username: project_service_user
    password: 9r8A1NciBpMKMVJd9ybBGwSotJ16mXTs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  rabbitmq:
      host: ${RABBITMQ_HOST:rabbitmq}
      port: ${RABBITMQ_PORT:5672}
      username: ${RABBITMQ_USERNAME:guest}
      password: ${RABBITMQ_PASSWORD:guest}
      virtual-host: ${RABBITMQ_VHOST:/}
      listener:
        simple:
          retry:
            enabled: true
            initial-interval: 3000   # 3 seconds
            max-attempts: 10
            multiplier: 2.0