version: '3.9'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin   # <-- Match with file-service
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped

  file-service:
    build:
      context: ../backend/file-service
      dockerfile: Dockerfile
    container_name: file-service
    ports:
      - "8080:8080"
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin      # <-- Same as MINIO_ROOT_USER
      MINIO_SECRET_KEY: minioadmin      # <-- Same as MINIO_ROOT_PASSWORD
      MINIO_BUCKET: files
    depends_on:
      - minio
    restart: unless-stopped

volumes:
  minio-data:
