
services:
  eureka-service:
    build:
      context: ../backend/eureka-service
      dockerfile: Dockerfile.dev
    container_name: eureka-server
    ports:
      - "8761:8761"
    volumes:
      - ../backend/eureka-service:/app
      - ~/.m2:/root/.m2
    command: [ "mvn", "spring-boot:run" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cloudide-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: cloudide-minio
    ports:
      - "9001:9001"
      - "9002:9002"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      retries: 20

  api-gateway:
    build:
      context: ../backend/api-gateway
      dockerfile: Dockerfile.dev
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka-service:
        condition: service_healthy
      project-service:
        condition: service_healthy
      file-service:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      auth-service:
        condition: service_started
      minio:
        condition: service_healthy
    volumes:
      - ../backend/api-gateway:/app
      - ~/.m2:/root/.m2
    command: ["mvn", "spring-boot:run"]
    environment:
      FRONTEND_URL: http://localhost:5173/
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s
    restart: unless-stopped

  auth-service:
    build:
      context: ../backend/auth-service
      dockerfile: Dockerfile.dev
    container_name: auth-service
    ports:
      - "8079:8079"
    depends_on:
      eureka-service:
        condition: service_started
    volumes:
      - ../backend/auth-service:/app
      - ~/.m2:/root/.m2
    command: [ "mvn", "spring-boot:run" ]
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: dev


  project-service:
    build:
      context: ../backend/project-service
      dockerfile: Dockerfile.dev
    container_name: project-service
    ports:
      - "8081:8081"
    depends_on:
      eureka-service:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    volumes:
      - ../backend/project-service:/app
      - ~/.m2:/root/.m2
    command: ["mvn", "spring-boot:run"]
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: dev
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_VHOST: /
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 20
      start_period: 10s

  file-service:
    build:
      context: ../backend/file-service
      dockerfile: Dockerfile.dev
    container_name: file-service
    ports:
      - "8082:8082"
    depends_on:
      eureka-service:
        condition: service_started
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    volumes:
      - ../backend/file-service:/app
      - ~/.m2:/root/.m2
      - workspaces:/var/lib/cloud-ide/workspaces
    command: ["mvn","spring-boot:run"]
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: userworkspace
      SPRING_PROFILES_ACTIVE: dev
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_VHOST: /
      FILE_SERVICE_WORKSPACE_DIR: /var/lib/cloud-ide/workspaces
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
    restart: unless-stopped

volumes:
  minio-data:
  workspaces:

