FROM maven:3.9.9-eclipse-temurin-21 AS dev
WORKDIR /app

# Install Docker CLI using Ubuntu’s docker.io package
RUN apt-get update && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/*

# Mount Maven cache
VOLUME ["/root/.m2"]

# Copy pom and prefetch deps
COPY pom.xml .
# RUN mvn dependency:go-offline -B

# Copy source
COPY src ./src

# Run in dev mode
CMD ["mvn","spring-boot:run"]
