server:
  port: 8082

spring:
  application:
    name: file-service
  datasource:
    url: jdbc:postgresql://dpg-d2li29juibrs73f99mu0-a.oregon-postgres.render.com/filedb_0gkn
    username: filedb_0gkn_user
    password: 4vE2QLPpiIvyK6XtJ39nOeMO1zo7tkOK
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  spring:
    rabbitmq:
      host: ${RABBITMQ_HOST:localhost}
      port: ${RABBITMQ_PORT:5672}
      username: ${RABBITMQ_USERNAME:guest}
      password: ${RABBITMQ_PASSWORD:guest}
      virtual-host: ${RABBITMQ_VHOST:/}


minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  bucket: ${MINIO_BUCKET:userworkspace}


