server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "your-secret-keyfweffdsfdbgsdfbfd"

  cloud:
    gateway:
      routes:
        # Auth service route
        - id: auth-service
          uri: http://auth-service:8083
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0

        # Project service route
        - id: project-service
          uri: http://project-service:8081
          predicates:
            - Path=/projects/**
          filters:
            - StripPrefix=0
            - UserIdRelayFilter

        # File service - files
        - id: file-service-files
          uri: http://file-service:8082
          predicates:
            - Path=/p/{projectId}/file/**
          filters:
            - StripPrefix=0

        # File service - folders
        - id: file-service-folders
          uri: http://file-service:8082
          predicates:
            - Path=/p/{projectId}/folder/**
          filters:
            - StripPrefix=0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
